version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  crypto-app:
    build:
      context: .
      dockerfile: Dockerfile.updated
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=crypto
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto
      - RESET_DB=false
      - BACKFILL_ON_START=true
      # Add your Binance API credentials here if needed
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      # Add your OpenAI API key if using OpenAI features
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data

volumes:
  postgres_data: