version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crypto
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Changed to port 5433 on host to avoid conflict
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  crypto-app:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=crypto
      - RESET_DB=true
      - BACKFILL_ON_START=true
      # Add your Binance API credentials here if needed
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      # Add your OpenAI API key if using OpenAI features
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "5001:5000" # Changed to port 5001 on host to avoid conflict
    volumes:
      - ./data:/app/data

volumes:
  postgres_data: