version: '3.8'

services:
  crypto-app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - RESET_DB=false
      - BACKFILL_ON_START=true
      # Add your Binance API credentials here if needed
      - BINANCE_API_KEY=${BINANCE_API_KEY:-}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET:-}
      # Add your OpenAI API key if using OpenAI features
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data